#pragma once
#ifndef MONSTERINFO_H
#define MONSTERINFO_H

enum
{
	MONSTERINFO_CLEAR = 0,
	MONSTERINFO_FULLUPDATE,
	MONSTERINFO_FASTUPDATE
};

#define MONSTERINFO_FLAG_NO 0
#define MONSTERINFO_FLAG_MONSTER (1<<0)
#define MONSTERINFO_FLAG_PLAYER (1<<1)
#define MONSTERINFO_FLAG_ALLY (1<<2)
#define MONSTERINFO_FLAG_MACHINE (1<<3)

#endif
