#!/usr/bin/env bash
#
# Clones and builds the Xash3D FWGS engine, then installs it into ./mod
# alongside the already-installed "featureful" gamedir, so the mod can be
# launched directly on Linux via mod/run.sh.
#
# Usage:
#   ./build-xash.sh            # clone (if missing), configure, build, install
#   ./build-xash.sh clean      # wipe the xash3d-fwgs build output and reconfigure
#   ./build-xash.sh update     # git pull + re-init submodules before building
#
# Engine build is 32-bit by default, matching this SDK's default game DLL
# architecture (mod/featureful/dlls/hl.so, mod/featureful/cl_dlls/client.so).

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

XASH_REPO="https://github.com/FWGS/xash3d-fwgs.git"
XASH_DIR="xash3d-fwgs"
MOD_DIR="$(pwd)/mod"
PATCH_DIR="$(pwd)/patches/xash3d"

if [[ "${1:-}" == "clean" ]]; then
	rm -rf "${XASH_DIR}/build"
	shift
fi

if [[ ! -d "$XASH_DIR" ]]; then
	git clone --recursive "$XASH_REPO" "$XASH_DIR"
elif [[ "${1:-}" == "update" ]]; then
	git -C "$XASH_DIR" pull
	git -C "$XASH_DIR" submodule update --init --recursive
	shift
fi

cd "$XASH_DIR"

# Apply local patches (patches/xash3d/*.patch, *.diff) before configuring/building.
# Idempotent: a patch that's already applied (source tree reused between runs)
# is detected via --reverse --check and skipped instead of failing.
shopt -s nullglob
patches=("$PATCH_DIR"/*.patch "$PATCH_DIR"/*.diff)
shopt -u nullglob
if [[ ${#patches[@]} -gt 0 ]]; then
	IFS=$'\n' patches=($(sort <<<"${patches[*]}")); unset IFS
	echo "Applying patches from $PATCH_DIR"
	for p in "${patches[@]}"; do
		if git apply --check "$p" 2>/dev/null; then
			git apply "$p"
			echo "  applied: $(basename "$p")"
		elif git apply --reverse --check "$p" 2>/dev/null; then
			echo "  already applied, skipping: $(basename "$p")"
		else
			echo "  FAILED to apply: $(basename "$p")" >&2
			exit 1
		fi
	done
fi

# 32-bit build on a 64-bit x86 host needs the i386 pkg-config path set,
# matching the FWGS README's Debian/Ubuntu 32-bit build instructions.
if [[ "$(uname -m)" == "x86_64" ]]; then
	export PKG_CONFIG_PATH="/usr/lib/i386-linux-gnu/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
fi

if [[ ! -d build ]]; then
	./waf configure
fi

./waf build

mkdir -p "$MOD_DIR"
./waf install --destdir="$MOD_DIR"

# (Re)generate mod/run.sh on every install: mod/ is entirely build output
# (git-ignored), so the launcher script needs to be regenerated here rather
# than kept as a hand-maintained file that a clean of mod/ would wipe.
cat > "$MOD_DIR/run.sh" <<'EOF'
#!/usr/bin/env bash
#
# Launches Xash3D with the "featureful" mod on Linux.
# Regenerated by build-xash.sh on every install - edit build-xash.sh, not
# this file, if it needs to change.
#
# Usage:
#   ./run.sh                # start listen server on the default demo map
#   ./run.sh +map somemap   # pass extra engine args straight through

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

GAMEDIR="featureful"

if [[ ! -x ./xash3d ]]; then
	echo "xash3d binary not found here. Run ../build-xash.sh first." >&2
	exit 1
fi

if [[ ! -d "./$GAMEDIR" ]]; then
	echo "Gamedir '$GAMEDIR' not found here. Install the mod build first." >&2
	exit 1
fi

exec ./xash3d -game "$GAMEDIR" -dev +developer 2 +sv_cheats 1 "$@"
EOF
chmod +x "$MOD_DIR/run.sh"

echo
echo "Xash3D engine installed into: $MOD_DIR"
find "$MOD_DIR" -maxdepth 1 -type f -exec ls -la {} \;
